name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate prisma
        run: npm run prisma:generate

      - name: Run tests and generate coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=victor-repo
            -Dsonar.projectKey=VictorlBueno_fiap-challenge-order-service-p4
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  deploy:
    name: Deploy AWS
    needs: sonarqube
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Build NestJS
        run: nest build

      - name: Generate prisma
        run: npm run prisma:generate

      - name: Set AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Serverless v3
        run: npm install -g serverless@3

      - name: Serverless Deploy
        run: serverless deploy